name: Update package

on:
  push:
    branches: [ main ]
  #pull_request:
  #  branches: [ main ]
  workflow_dispatch:

jobs:

  updateOPack:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      
    steps  :
    # --------------------------
    - name: Cache OpenAF runtime
      uses: actions/cache@v3
      with:
        key : oaf-t8
        path: /tmp/oaf
        
    # -------------------------
    - uses: actions/checkout@v2
        
    # ------------------
    - name: Update opack
      uses: openaf/ojob-action@v3
      with:
        script: |
          $sh("opack genpack .")
          .prefix("opack")
          .get()
        dist  : t8
        
    # ---------------------
    - name: Commit and push
      uses: openaf/ojob-action@v3
      with:
        ojob: 'ojob.io/git/githubCheckIn'
        args: 'message=update\ pack'
        dist: t8
